// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;



public class AuthTests {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "C:/Users/f0urth/IdeaProjects/geckodriver.exe");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void loginTestPositive() {
        driver.get("http://point3.smart-consulting.ru/");
        driver.manage().window().setSize(new Dimension(885, 693));
        login("user", "user");
    }

    private void login(String user, String password) {
        driver.findElement(By.id("auth-username")).sendKeys(user);
        driver.findElement(By.id("auth-password")).sendKeys(password);
        driver.findElement(By.cssSelector(".btn-primary")).click();
    }
}
